import { Case } from './types'

export const BUILTIN_CASES: Omit<Case, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'Vernieling parkeerplaats supermarkt',
    crimeType: 'vernieling',
    legalArticle: 'Art. 350 Sr',
    description: 'Een geparkeerde auto is bekrast op de parkeerplaats van een supermarkt.',
    backgroundStory: `Op dinsdag 4 februari 2025, omstreeks 14:30 uur, werd op de parkeerplaats van de Albert Heijn aan de Hoofdstraat 45 te Utrecht, een personenauto (blauwe Volkswagen Golf, kenteken AB-12-CD) flink bekrast. De gehele linkerzijkant is met een scherp voorwerp bewerkt. Schade wordt geschat op €1.800.

De eigenaar van het voertuig, de heer Van Dijk, deed aangifte. Hij stond binnen in de supermarkt te winkelen. Getuige Mevr. Janssen zag de dader: een jongeman van ongeveer 20 jaar, gekleed in een rode hoodie en spijkerbroek, die bewust langs de auto liep en er iets tegen aan trok.`,
    intervieweeType: 'getuige',
    witnessName: 'Maria Janssen',
    witnessAge: 54,
    witnessGender: 'vrouw',
    voiceId: 'nova',
    witnessPhoto: 'https://randomuser.me/api/portraits/women/68.jpg',
    witnessProfile: 'Mevrouw Janssen is een nette, rustige vrouw van middelbare leeftijd. Ze was net haar boodschappen aan het uitladen bij haar auto, die naast de beschadigde auto stond. Ze heeft alles goed gezien en is bereid te verklaren.',
    witnessKnows: [
      'Tijdstip: omstreeks 14:30 uur',
      'Locatie: parkeerplaats Albert Heijn, Hoofdstraat 45, Utrecht',
      'Dader: jongeman, circa 20 jaar, rood hoodie, spijkerbroek, donker haar',
      'Dader liep bewust langs de auto en trok er iets (sleutel?) langs de zijkant',
      'Dader liep daarna snel weg richting de uitgang van het parkeerterrein',
      'Er was niemand anders in de directe omgeving',
      'De dader keek even om na het incident',
      'Getuige heeft geen auto van de dader gezien',
    ],
    keyDiscoveries: [],
    cooperationLevel: 2,
    isTemplate: true,
    status: 'published',
    createdBy: 'system',
  },
  {
    title: 'Heling gestolen fiets via Marktplaats',
    crimeType: 'heling',
    legalArticle: 'Art. 416 Sr',
    description: 'Een gestolen fiets werd te koop aangeboden via Marktplaats. De koper heeft de fiets gekocht en twijfelde achteraf.',
    backgroundStory: `Op donderdag 6 februari 2025 deed de heer Peters aangifte van diefstal van zijn mountainbike (merk Trek, zwart, waarde €650) op zaterdag 1 februari uit zijn achtertuin in Eindhoven.

Op maandag 3 februari zag zijn buurman, de heer Kowalski, een identieke fiets op Marktplaats voor €200. Hij kocht de fiets, maar zijn vrouw zei dat hij beter moest controleren of de fiets wel gestolen was. De heer Kowalski is nu bereid te verklaren over de aankoop. Hij heeft contact gehad met de verkoper via WhatsApp en heeft hem ook ontmoet.`,
    intervieweeType: 'getuige',
    witnessName: 'Adam Kowalski',
    witnessAge: 38,
    witnessGender: 'man',
    voiceId: 'onyx',
    witnessPhoto: 'https://randomuser.me/api/portraits/men/42.jpg',
    witnessProfile: 'De heer Kowalski is een Poolse man die al 10 jaar in Nederland woont. Hij spreekt goed Nederlands. Hij kocht de fiets in goed vertrouwen maar begrijpt nu dat hij mogelijk heling heeft gepleegd. Hij is zenuwachtig maar wil meewerken.',
    witnessKnows: [
      'Kocht de fiets op maandag 3 februari voor €200 cash',
      'Ontmoeting vond plaats op het Centraal Station Eindhoven, om 18:00 uur',
      'Verkoper was een man van circa 25-30 jaar, getinte huid, normaal postuur, zwarte jas',
      'Communicatie via Marktplaats en WhatsApp (heeft berichten nog op telefoon)',
      'Heeft telefoonnummer van de verkoper (kan dit geven)',
      'Verkoper zei dat hij de fiets verkocht omdat hij een nieuwe had gekregen',
      'Geen bon of bewijs van eigendom gevraagd',
      'Fiets staat nu in zijn schuur',
    ],
    keyDiscoveries: [],
    cooperationLevel: 2,
    isTemplate: true,
    status: 'published',
    createdBy: 'system',
  },
  {
    title: 'Winkeldiefstal kledingwinkel',
    crimeType: 'diefstal',
    legalArticle: 'Art. 310 Sr',
    description: 'Kleding werd gestolen in een kledingwinkel. De beveiligingsmedewerker zag alles.',
    backgroundStory: `Op vrijdag 7 februari 2025, omstreeks 15:45 uur, vond in modezaak "Fashion Point" aan de Kalverstraat 88 te Amsterdam een winkeldiefstal plaats.

Een vrouw nam drie truien (totale waarde €179) van het rek, stopte deze in een grote tas en verliet de winkel zonder te betalen. Beveiligingsmedewerker Mohammed El Bakri hield haar staande bij de uitgang. De vrouw maakte zich los en rende de straat op. Ze is ontsnapt maar wel gefilmd door de beveiligingscamera.`,
    intervieweeType: 'getuige',
    witnessName: 'Mohammed El Bakri',
    witnessAge: 29,
    witnessGender: 'man',
    voiceId: 'echo',
    witnessPhoto: 'https://randomuser.me/api/portraits/men/22.jpg',
    witnessProfile: 'Mohammed is een professionele, oplettende beveiligingsmedewerker met 5 jaar ervaring. Hij is gewend om aan te geven en weet hoe een getuigenverklaring werkt. Hij is direct en zakelijk.',
    witnessKnows: [
      'Tijdstip: omstreeks 15:45 uur',
      'Locatie: Fashion Point, Kalverstraat 88, Amsterdam',
      'Signalement dader: vrouw, circa 30 jaar, lang blond haar, groene jas, zwarte broek, grote bruine tas',
      'Drie truien gestolen, totaalwaarde ca. €179',
      'Zag hoe de vrouw de truien van het rek pakte en in haar tas stopte',
      'Beveiligingscamera heeft alles opgenomen (beelden bewaard)',
      'Heeft de vrouw staande gehouden bij de uitgang, zij maakte zich los en rende weg',
      'Richting vlucht: naar rechts de Kalverstraat op',
      'Geen medeplichtigen gezien',
    ],
    keyDiscoveries: [],
    cooperationLevel: 1,
    isTemplate: true,
    status: 'published',
    createdBy: 'system',
  },
  {
    title: 'Mishandeling bij café',
    crimeType: 'mishandeling',
    legalArticle: 'Art. 300 Sr',
    description: 'Vechtpartij voor een café op zaterdagnacht. Een voorbijganger zag de mishandeling.',
    backgroundStory: `Op zaterdag 8 februari 2025, omstreeks 02:15 uur, vond voor café "De Kroeg" aan de Grote Markt 12 te Groningen een vechtpartij plaats.

Twee mannen raakten slaags. Één man viel de ander aan en sloeg hem meerdere keren in het gezicht. Het slachtoffer viel op de grond. De aanvaller liep weg voordat de politie arriveerde. Het slachtoffer heeft een gebroken neus en snijwond boven zijn oog. Getuige Lena de Vries liep toevallig langs en zag het incident.`,
    intervieweeType: 'getuige',
    witnessName: 'Lena de Vries',
    witnessAge: 24,
    witnessGender: 'vrouw',
    voiceId: 'shimmer',
    witnessPhoto: 'https://randomuser.me/api/portraits/women/26.jpg',
    witnessProfile: 'Lena is een studente die na een avond stappen naar huis liep. Ze is aangeslagen door wat ze heeft gezien maar wil helpen. Ze heeft gedronken die avond (niet overdreven, maar relevant voor betrouwbaarheid) en is soms vaag in haar details.',
    witnessKnows: [
      'Tijdstip: rond 02:15 uur s\'nachts',
      'Locatie: voor café De Kroeg, Grote Markt 12, Groningen',
      'Aanvaller: man, ongeveer 1.85m, stevig gebouwd, kaal hoofd, blauw shirt',
      'Slachtoffer: man, gemiddeld postuur, donker haar, wit overhemd dat besmeurd raakte met bloed',
      'Aanvaller sloeg het slachtoffer meerdere keren met gebalde vuist in het gezicht',
      'Slachtoffer viel achterover op de grond',
      'Aanvaller liep daarna rustig weg richting het centrum',
      'Er waren meer mensen buiten maar die bleven op afstand',
      'Heeft geen telefoon bij de hand gehad om te filmen',
    ],
    keyDiscoveries: [],
    cooperationLevel: 3,
    isTemplate: true,
    status: 'published',
    createdBy: 'system',
  },
  {
    title: 'Inbraak in tuinschuur',
    crimeType: 'inbraak',
    legalArticle: 'Art. 311 Sr',
    description: 'Inbraak in een tuinschuur van een woning. De buurvrouw zag een verdachte persoon rondlopen.',
    backgroundStory: `Op woensdag 5 februari 2025, omstreeks 11:00 uur, werd ingebroken in de tuinschuur van de woning aan de Acaciastraat 7 te Den Haag. Uit de schuur werden gestolen: een grasmaaier (waarde €350), elektrisch gereedschap (totaal ca. €600) en een fiets (€200).

De bewoners waren niet thuis. Buurvrouw Riet Verhoeven zag vanuit haar keukenraam een onbekende man in de tuin. Ze dacht er niet direct bij na maar herinnerde het zich later toen ze de politieauto voor de deur zag staan.`,
    intervieweeType: 'getuige',
    witnessName: 'Riet Verhoeven',
    witnessAge: 71,
    witnessGender: 'vrouw',
    voiceId: 'coral',
    witnessPhoto: 'https://randomuser.me/api/portraits/women/75.jpg',
    witnessProfile: 'Mevrouw Verhoeven is een gepensioneerde dame die de hele dag thuis is. Ze zit veel bij haar keukenraam. Ze is bezorgd en wil wel helpen maar haar geheugen is niet perfect. Ze is ook een beetje bang dat ze in de problemen komt als ze iets verkeerds zegt.',
    witnessKnows: [
      'Zag omstreeks 11:00 uur een onbekende man in de achtertuin van de buren',
      'Man was alleen, circa 40 jaar, normaal postuur, grijze werkkleding',
      'Man droeg een grote rugzak of tas',
      'Man liep meerdere keren heen en weer tussen de schuur en de tuinmuur',
      'Dacht dat het misschien een aannemer was (twijfelt hierover)',
      'Heeft geen gezicht goed gezien (keek van achter het raam)',
      'Zag de man over de tuinmuur klimmen aan de zijkant',
      'Heeft niks gedaan op dat moment',
      'Weet niet of er een voertuig was',
    ],
    keyDiscoveries: [],
    cooperationLevel: 3,
    isTemplate: true,
    status: 'published',
    createdBy: 'system',
  },
]
